# Generated by Django 4.1.3 on 2022-11-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
