# Generated by Django 4.1.3 on 2022-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapi", "0002_author_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year_of_creation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year_of_publication",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="description",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="year_of_foundation",
            field=models.DateField(blank=True, null=True),
        ),
    ]
