# Generated by Django 4.1.3 on 2022-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapi", "0003_alter_author_biography_alter_author_date_of_death_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookquote",
            name="text",
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="books",
            field=models.ManyToManyField(related_name="publishers", to="bookapi.book"),
        ),
    ]
