# Generated by Django 4.1.3 on 2022-11-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapi", "0004_alter_bookquote_text_alter_publisher_books"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=356)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bookapi.book"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="BookGenre",
            new_name="Genre",
        ),
        migrations.RenameModel(
            old_name="BookQuote",
            new_name="Quote",
        ),
        migrations.DeleteModel(
            name="BookReview",
        ),
    ]
