# Generated by Django 4.1.3 on 2022-11-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookapi",
            "0005_review_rename_bookgenre_genre_rename_bookquote_quote_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="publisher",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                error_messages={"unique": "This genre already exists."},
                max_length=64,
                unique=True,
            ),
        ),
    ]
