# Generated by Django 4.1.3 on 2022-11-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapi", "0007_alter_publisher_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="publishers", to="bookapi.book"
            ),
        ),
    ]
